### ISSUE TITLE
Create releases

### ISSUE THREAD

**Issue by avstudnitz** [mage-os/mageos-async-events#15]
If we want to include this module via composer, a release would be very helpful. I'd suggest creating a 3.0 and a 2.0 release.

@gowrizrh @aligent-lturner Thanks for your great work on this module!

**Comment by gowrizrh** [comment]
I've created a new release and bumped one minor version up from the ported project. `v3.2.0` and `v2.6.0-beta` (as I haven't tested it since). If anyone's willing to do that before I get to it we can release a stable release, if not it might be a while until I get to it.

**Comment by avstudnitz** [comment]
Thank you! Due to a configuration error, I didn't receive and emails from GitHub, so I've just seen it now.
