### ISSUE TITLE
Use main Branch Instead Of 3.x?

### ISSUE THREAD

**Issue by sprankhub** [mage-os/mageos-async-events#9]
When https://github.com/mage-os/terraform/issues/44 is finished, it should be possible to configure the default branch via Terraform. However, I wonder why we shouldn't just use the `main` branch for the latest 2.4-compatible version of this extension. I suggest simply renaming / moving the branch `3.x` to `main`. Is there any reason against this, @gowrizrh? Thanks!

**Comment by gowrizrh** [comment]
we could. i've been only managing a release line like `2.x` or `3.x` via long lived branches. that way when want to backport a change to the relevant major version we could simply merge in a PR. if there's a better way to manage multiple release versions then i'm happy to  take a look.

**Comment by sprankhub** [comment]
IMHO, it absolutely makes sense to have separate branches if you really need separate codebases for e.g. 2.3/2.4. However, I would only create separate branches for old versions (like the `2.x` branch for Magento 2.3). I think the current codebase compatible with the latest version could still be in the `main` branch.

**Comment by gowrizrh** [comment]
the advantage of having separate branches mean that their corresponding release tags will always reside in their dedicated branch as opposed to being in the main branch during whenever that major version is on the main branch but as soon as you create another major version, they'll have to go into their dedicated branch.

![image](https://user-images.githubusercontent.com/40108018/228754508-63f2d2db-2a2f-4fc9-bdc8-1ff4a8d93e12.png)

it's not a big deal eitherway, but the idea of a branch holding its release line makes sense to me. i just took this model of from lumen or laravel.

alternatively we could keep merging the current release line back into main periodically. but i'd rather prefer to switch the default branch as we keep releasing new major versions.

**Comment by sprankhub** [comment]
Okay, all fine. I added support for this in https://github.com/mage-os/terraform/pull/48 and changed the default branch of this repository to `3.x`.
